:toc-title: Table of Contents
:toc:
:toclevels: 5
= Getting Started

== [[COMBINE]]Combine goal

=== Configuration and parameters

To configure the combine goal the following options are available:

[[options]]
.options
[cols="1,2,1"]
|===
|Option name|Description|Default
|templateDir|Path to the directory of the templates|./src/test/resources/templates
|outputDir|Path to the directory where the rendered templates got stored|./src/test/resources/features
|[[combineItemsFile]]combineItemsFile|Path to json file that contains the values to combine. More info on this file <<combine_items,here>>.|./src/test/resources/combine_items.json
|ending|The specific ending of the templates|.cute
|skipScenariosWithoutExamples| If *true* plugin will add tags '@WIP' and '@EMPTY_EXAMPLES_TABLE' to an examples table where the plugin was not able to add at least one row |true
|minTableSize|Amount of minimal rows in one table. If table have less rows error log will be written. Can be conbined with *breakIfTableToSmall*|1
|breakIfTableToSmall|If *true* the plugin will raise an error if it`s not able to add the minimal amount of rows that are requested in property minTableSize|true
|breakIfMinimalTableError|If *true* the plugin will raise an error if there is at least one value that could not apply due row-filters. This does not include all values that are excluded by colum-filters|false
|defaultExamplesTags|List of tags that are added to each table as default.
@AllowDoubleLineup, @AllowSelfCombine and @MinimalTable are forbidden. Their default should be set in filterConfiguration.| empty
|pluginTagCategory|Define a category to be placed before every plugin-specific tag (except for version filter tags, see below), so they don't get mixed with all the other tags in the document with important information.|"Plugin"
|projectFilterTagCategory|Like pluginTagCategory, but especially for *version filter* tags.|"VersionFilter"
|[[versionProperty]]versionProperty|Specify the name of the item property (from <<combine_items, combine_items.json>>) the plugin will use to filter for versions.|"version"
|[[filterConfiguration]]filterConfiguration| Configuration for default filter behavior, see options below: <<filter-configuration, filterConfig options table>> | see <<filter-configuration, table>>
|[[projectFilters]]projectFilters|Set filters that are used across the entire project, see options below: <<project-filters, projectFilters table>>|None
|===

[[filter-configuration]]
.filterConfiguration (within <<options>>)
[cols="1,2,1"]
|===
|Option name|Description|Default
|allowSelfCombine[[allowSelfCombine]]|If *true* plugin will allow that an item can be combined with itself|false
|allowDoubleLineup[[allowDoubleLineup]]|If *true* plugin will allow that one combination of items can appear multiple times if differently sorted|false
|minimalTable[[minimalTable]]|If *true* plugin will always generate a table with minimal number of entries|false
|[[maxTableRows]]maxTableRows|Set a maximum of rows per table

_override with <<config_tag_maxrows, @MaxRows>>_|Integer.MAX_VALUE
|[[shuffleCombinations]]shuffleCombinations|If *true* plugin will shuffle the table rows

_override with <<config-tag-shuffle, @Shuffle>>_|false
|===


[[project-filters]]
.projectFilters (within <<options>>)
[%header, cols="1,3,1"]
|===
|Option name|Description|Default
|[[versionProjectFilter]]version a|Set a global version filter that will be used in every examples table unless it is explicitly overridden there with a <<version-filter, @Version(...) filter>>.

IMPORTANT: *In pom.xml only the bash-style operators can be used!* (see <<operators, Operators>>)

_Note that the global version filter will still be applied to columns that do not have a version filter set to them._

_A global version filter can not be set to (a) specific column header(s). Any column headers set in it will be *ignored*._

.example:
****
* we have a table with columns: *col1*, *col2*, *col3*, *col4*
* global version filter is set to *--EQ\--0.8.15*
* on the table, the following tags are set:
** *@Version(col1,col2>4.20)*
** *@Version(col3\<=4.20)*
****
.result:
****
=> *greater than 4.20* will be used for col1 and col2

=> *less than or equal 4.20* will be applied to col3

=> global filter *equals 0.8.15* will be applied to col4
****

Read more about version filters <<version-filter, here>>

|None

|===


=== What else do I need?

==== [[combine_items]]An input file

The file handed to the plugin goal via the <<combineItemsFile, combineItemsFile>> parameter in <<options, options>>.
It must be a json file and contain an array of the items to combine.
Each item needs a `value` field and can have a list of `tags` and a map of `properties`:

.example input file
[source,json]
----
[
  {
    "value": "http://item1",
    "tags": [
      "tag1",
      "tag2"
    ],
    "properties": {
      "homeserver": "A",
      "version": "4.20"
    }
  },
  {
    "value": "http://item2",
    "tags": [],
    "properties": {
      "homeserver": "B",
      "version": "0.8.15"
    }
  }
]
----

[NOTE]
====
If you want to use the <<PREPARE, Prepare Goal>>, the items must have a value that can be set and must be set as the <<infoResourceLocation, infoResourceLocation>>.

You can *EITHER* use a base _combine_items.json_ file which is then completed by the <<PREPARE, Prepare Goal>>. <<PREPARE, It>> asks all the specified endpoints for the information and outputs to a file located at `.target/generated-combine/combine_items.json`. You can then use that output as the <<combineItemsFile, input>> for the <<COMBINE, Combine Goal>>.

*OR* you can just use a complete _combine_items.json_ file with running the <<COMBINE, Combine Goal>> only, specifying your prepared input file via <<combineItemsFile, combineItemsFile>>.
====

==== Templates

In the template files you can specify an empty examples table with only header values.
The plugin will insert the table body according to its configuration.
Over the table you can use predefined gherkin tags to customize the table generation.
If you choose no tags for a scenario, all items will be included in the table rendering.

.example template file
[source,gherkin]
----
...

  Scenario Outline: Get devices
    Given claim client gematik on api <ApiName1>
    When get all devices
    Then returns devices information

    Examples:
    |ApiName1|

  Scenario Outline: Get orgAdmin devices
    Given claim client gematik on api <ApiName1>
    When get all devices
    Then returns devices information

    @Filter(ApiName1.hasTag("orgAdmin"))
    Examples:
    |ApiName1|

...
----

===== Configuration Tags

Configuration tags can override the default configuration values for a single examples table.
Configuration tags with a boolean value have default values for which the value can be omitted e.g. `@Shuffle(true)` can also be written as `@Shuffle`

.configuration tags
[cols="2,1,4"]
|===
|Tag name|Default|Example
|[[config_tag_AllowDoubleLineup]]@AllowDoubleLineup(<boolean>)

Example:
@AllowDoubleLineup(true)|true|Specifies if one combination of items can appear multiple times in the examples table, if sorted differently.

e.g. Row "\|entry2\|entry1\|" will not appear if row "\|entry1\|entry2\|" is present.

Can override the <<allowDoubleLineup, allowDoubleLineup>> option.

|[[config_tag_AllowSelfCombine]]@AllowSelfCombine(<boolean>)

Example:
@AllowSelfCombine(false)|true|Specifies if an item can be combined with itself.

e.g. Row "\|entry1\|entry1\|" will not appear if SelfCombine is disabled.

Can override the <<allowSelfCombine, allowSelfCombine>> option.

|[[config_tag_mintable]]@MinimalTable(<boolean>)

Example:
@MinimalTable(true)|true a|Generate a table with minimal number of entries. Each possible entry will occur in the resulting table as long as there are sufficient items to fill each row. If additional entries are needed to fill the last row, items will be reused.
Using cell and row filters may lead to the plugin having to reuse items multiple times even in MinimalTable mode.

DoubleLineup is always deactivated in such a table.

IMPORTANT: Only cell and row filters are evaluated in table generation.
Table filters will be applied after table generation. Therefore, this table can not be filtered with table filter tags without loosing multiple entries completely.

WARNING: This may cause different results under certain circumstances (e.g. in combination with shuffle or different filters for every column). To avoid this, apply the most restrictive filters to the first column.

Can override the <<minimalTable, minimalTable>> option.
|[[config_tag_maxrows]]@MaxRows(<int>)

Example: @MaxRows(1)|- a|Set a maximum of rows in this table.

[IMPORTANT]
====
*"MaxRows" is also used for a <<table_filter_maxrows,TableFilter-Tag>>. The type of created filter is determined by the value for this tag:*

* for simple integer values it is interpreted as configuration tag, that overrides maxRows-config
* for everything else the table filter is used, which does not override the configuration value
====

Can override the <<maxTableRows, maxTableRows>> option.
|[[config-tag-shuffle]]@Shuffle(<boolean>)

Example: @Shuffle(true)|true|Shuffle the table, this can be interesting if you want to limit the table size but still want to get different lines in the mix than the ones which are first generated by pure arithmetic logic.

Can override the <<shuffleCombinations, shuffleCombinations>> option.
|===

===== Row Filter Tags

Filter tags can filter out possible table rows by given parameters.

.filter tags
[cols="1,2"]
|===
|Tag name|Description
|@Filter(<expression>)

Example:
@Filter(HEADER_1.hasTag("orgAdmin")) a|
In this filter you can assign an expression to a table column that must return *true* for a link:src/main/java/de/gematik/combine/model/CombineItem.java[CombineItem] to be placed in that column. Columns are identified by referencing its header.

By placing an _exclamation mark_ before an expression the boolean returned by it can be negated. Example: `@Filter(##!##COL.hasTag("XY"))`
The ##!## can be read as *_not_*.

[[filter-expressions]]
.filter expressions

* `COL.hasTag("XY")`
** will only let items be placed in *COL* if they have the tag *XY*
* `!COL.hasTag("XY")`
** will only let items be placed in *COL* if they *do not* have the tag *XY*
* `COL1.properties["XY"].equals("value")`
** will only let items be placed in *COL* if they have the property *XY* set to "_value_"
* `!COL1.properties["XY"].equals("value")`
** will only let items be placed in **C**OL if they *do not* have the property *XY* set to "_value_"
* `COL1.properties["XY"].equals(COL2.properties["XY"])`
** Will only use rows in which the item in *COL1* has the same property value set for *XY* as the item in *COL2* does
* `!COL1.properties["XY"].equals(COL2.properties["XY"])`
** Will *remove* rows in which the item in *COL1* has the same property value set for *XY* as the item in *COL2* does


NOTE: If you want the items of all columns in a row to have equal or distinct values for a property, use the <<DistinctProperty, @DistinctProperty>> or <<EqualProperty, @EqualProperty>> filter tags!

.examples
* `@Filter(H1.hasTag("client"))`
* `@Filter(!H1.hasTag("orgAdmin"))`
* `@Filter(H1.properties["home"].equals(H2.properties["home"]))`
* `@Filter(!H2.properties["home"].equals("gematik")`






The expression itself, if you are looking for a deep-dive read, is a https://commons.apache.org/proper/commons-jexl/reference/syntax.html[JEXL-Expression].

IMPORTANT: *`@Filter` tags that only reference one column will be applied to columns before generating the table and can reduce the amount of filtering significantly.*
|[[EqualProperty]]@EqualProperty(<propertyName>)

Example:
@EqualProperty(homeserver)|In a row, all items must have the given property set to the same value.
|[[DistinctProperty]]@DistinctProperty(<propertyName>)

Example:
@DistinctProperty(homeserver)|No item in a row can have the same value of the given property, meaning in a row every item must have a different value set for the given property
|[[version-filter]]@Version(<column(s)><operator><version>)

Examples:

@Version(HEADER_1\--GE\--2.2.1)

@Version(HEADER_1,HEADER_3==5.1)
a|In the given column(s), a cell must

* have a version property: the name of that property can be set via the <<versionProperty, versionProperty>> variable in <<options, options>>; the plugin will use that name to look for a version property in each items´ properties

* return true on the version filter condition set by the expression in the filter

otherwise every row containing that cell will be removed.

The version parameter must be of the form X , X.X , X.X.X or X.X.X.X etc., with X being integers only.

A version filter can be applied to multiple columns by giving a comma-seperated list of column headers.

Available operators are the standard https://en.cppreference.com/w/cpp/language/operator_comparison#Two-way_comparison[two-way comparison operators]. In a `@Version()` filter both bash-style and math-style operators can be used interchangeably.

[[operators]]
.comparison operators
[cols="1,1,3"]
!===
!bash-style !math-style !description
!--EQ--
!==
!*equals* (note that version 1 == 1.0 == 01.0.0)

!--NE--
!\!=
!*does not equal*

!--LT--
!<
!*less than*

!--LE--
!\<=
!*less than or equal*

!--GT--
!>
!*greater than*

!--GE--
!>=
!*greater than or equal*
!===

Can override a <<versionProjectFilter, version projectFilter>> _for the columns it is referencing only!_.

|===

===== [[table_filter_tags]] Table Filter Tags

Table filter tags can filter the whole table and are not bound to a row.

.table filter tags
[cols="1,2"]
|===
|Tag name|Description
|@DistinctColumn(<columnName>)

Example:
@DistinctColumn(HEADER_1)|In the given column every item will only appear once.
|
[[table_filter_maxrows]]@MaxRows(<expression>)

Examples:

@MaxRows(1+2)

@MaxRows(HEADER_1.properties["homeserver"].distinct().count()*2)
a|Sets a maximum of rows in this table.

This is an extended version of the config tag <<config_tag_maxrows,MaxRows>> that can evaluate https://commons.apache.org/proper/commons-jexl/reference/syntax.html[JEXL-Expressions]. As well as arithmetic operations you can access items properties and use them to create an integer that then will be used as in <<config_tag_maxrows, @MaxRows()>>

In the expression you can access the columns with its header name and use it like a link:src/main/java/de/gematik/combine/filter/jexl/JexlFilterColumn.java[JexlFilterColumn].

Additionally, the variables 'rowCount' and 'columnCount' are usable.

IMPORTANT: This filter does not override the configuration value for maxRows.
|@MaxSameColumnProperty(<columnName>,<propertyName>,<count>)

Example:

@MaxSameColumnProperty(HEADER_1,homeserver,2)
a| counts the occurrences of the given property values in the given column and removes rows with property value occurrences over the given count.
|@DistinctColumnProperty(<columnName>,<propertyName>)

Example:

@DistinctColumnProperty(HEADER_1,homeserver)
a| Leaves only one row for each distinct property value in the given column.
Works as MaxSameColumnProperty-Tag with count 1.
|===

== [[PREPARE]]Prepare goal

It parses the info-endpoint and adds additional information and validates all given information automatically. It takes the base combine_items.json and creates a new one regarding the info-data endpoint and the given expressions. The info-point could be parsed by JSON-Path which are configured in expressions.

Only if there is a configuration for a specific tag or property it will validate. All tags or properties that have no configuration will be copied 1 to 1 in the resulting combine_items.json.

Depending on configuration the plugin exits with an error or overrides all information with the findings at the info-endpoint.

IMPORTANT: *If you want to use this goal, it has to be executed before the combine goal!*

=== Configuration and parameters

[[prepare-options]]
.prepare options
[%header, cols="1,2,1"]
|===
|Option name|Description|Default
|combineItemsFile|Path to json file that contains the values to prepare. <<combine_items,click here for further information>>|"./src/test/resources/
combine_items.json"
|infoResourceLocation[[infoResourceLocation]]|Location to the info-endpoint, if this is not he root location. For example if the URL is localhost:8080 and the info-endpoint is at /app/info you have to provide app/info here.|
|tagExpressions|This is a list of complex data and define which tags have to be set under what conditions. Read more here <<Expressions>>|
|propertyExpressions|This is a list of complex data and define which property have to be set under what conditions. Read more here <<Expressions>>|
|truststore|Path of truststore|
|truststorePw|Truststore password|
|clientCertStore|Path of client-cert-store|
|clientCertStorePw|Client-cert-password|
|hardFail|If one API is not reachable the plugin will raise an exception|true
|configFail|If one tag or one property should be set or differs from the given the plugin will raise an exception. If set to false all information from the infopoint will override the given information|true
|===


==== [[Expressions]] Expressions

Every single expression you configure is a check that should be done against the info-endpoint. This expression got executed and compared to the info-endpoint.

A tag expression (JSON-Path) should have a true or false as result. If the result of the path is true the tag will be added or kept. If the result is false the tag will be ignored (no error) or unset if the tag is named in the base combine_item.json.

This results in following table of outcomes:

.Result table tags
[%header,cols="2,2,2,1"]
|===
|Value in base|Value in api|result|error
|is set|true|tag is set|no
|is not set|true|tag is set|no
|is set|false|tag is removed|yes
|is not set|false|tag is ignored| no
|===

If the path for a property is existing, the value will be added. If the path does not exist but the property is set in the base combine_items.json the property stays. If no property is set in the base combine_items.json and the path does not exist, the property will be removed. In addition to the tag, the set value in the base combine_items.json will be compared to the value found at the info-endpoint and will raise an exception if configured, but at least noticed in error log.

This results in following table of outcomes:

.Result table properties
[%header, cols="2,2,2,1"]
|===
|Value in base|Value in api|result|error
|is set|found and is same|property is set|no
|is set|found and differs from base|property got overwritten by api value|yes
|is not set|found|property is set|no
|is set|not found|property is removed|yes
|is not set|not found|tag is ignored| no
|===

Everytime an expression is not successful (returns false or was not found) the build will break if `configFail` is set to true (default). If it's set to false the regarding tag or property will be removed if set. In this case an errorLog.txt file with all registered errors will be generated right next to the generated combine_items.json at `./target/generated-combine`.

==== Configuration in pom.xml
.Example tag and property Expression
[source, xml]
----
<configuration>
  <tagExpressions>
    <tagExpression>
      <tag>MyTag</tag>
      <expression>$.my.Json.Path</expression>
    </tagExpression>
    <tagExpression>
      ...
    </tagExpression>
  </tagExpressions>
  <propertyExpressions>
    <propertyExpression>
      <property>myProperty</property>
      <expression>$.my.Json.Path</expression>
    </propertyExpression>
    <propertyExpression>
      ...
    </propertyExpression>
  </propertyExpressions>
</configuration>
----

=== Using mTls

For using mTls all 4 properties have to be set:

. truststore
. truststorePw
. clientCertStore
. clientCertStorePw

If one of these properties is set and the others not, or it's mal configuration, the plugin will raise an error. For using only https none of this properties have to be set. The plugin uses the internal truststore as default.

=== Error log

Every error / mismatch that exist between the base combine_items.json will be logged to console and also to the folder ./target/generated-combine. This enables you for a proper investigation.